FROM liquibase/liquibase:4.33

WORKDIR /workspace

ADD --chmod=644 https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.0.0/mysql-connector-j-9.0.0.jar /liquibase/lib/mysql-connector-j-9.0.0.jar
